### ISSUE TITLE
syscall error: data not found by data hash: H256([151, 153, ..., 10, 244])

### ISSUE THREAD

**Issue by Kuzirashi** [RetricSu/godwoken-kicker#12]
Using following Solidity smart-contract: 
- Solidity code: https://gist.github.com/Kuzirashi/93783e8428bdfba57898217d981a5d49
- Compiled contract artifact: https://gist.github.com/Kuzirashi/3b95e7b8ebdc673abe558771c00d16ca
- Binary bytecode: https://gist.github.com/Kuzirashi/0f7112f79c7d45d7fb786fcaa65a07fd

And calling:
```
function verify(bytes32 hash, bytes memory signature) public pure returns (address) {
    return recover(toEthSignedMessageHash(hash), signature);
}
```

With following parameters:
```
const hash = '0x8ab0890f028c9502cc20d441b4c4bb116f48ea632f522ac84e965d1dadf918e1';
const signedHash = '0xaaa99f644a5c4447314c5b7fcfac80deb186218aca1edaa63711aa75eb36585b47743901ce20f32768c7108bf85457ee0f16020f9bebc2bf456d6094c1c923c11c';
const fromAddress = '0xD173313A51f8fc37BcF67569b463abd89d81844f';

contract.methods.verify(hash, signedHash).call({
    from: fromAddress,
    gas: 5000000
});
```

Results in RPC error:
```
Uncaught (in promise) Error: failed to send gw_executeL2Tranaction rpc, {"jsonrpc":"2.0","id":"18b3fb80-58ad-401a-9552-d89c254cc712","error":{"code":-32603,"message":"Internal error"}}
```

And following Godwoken log:
```
godwoken_1             | [contract debug]: BEGIN call
godwoken_1             | [contract debug]: call.sender 0x0e00000000000000000000000000000000000000
godwoken_1             | [contract debug]: call.destination 0x0000000000000000000000000000000000000001
godwoken_1             | syscall error: data not found by data hash: H256([151, 153, 190, 226, 81, 185, 117, 184, 44, 69, 160, 33, 84, 206, 40, 206, 200, 156, 88, 83, 236, 193, 77, 18, 183, 184, 204, 207, 193, 158, 10, 244])
```

`recover` function is from OpenZeppelin ECDSA lib: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol

**Comment by RetricSu** [comment]
this turns out to be a bug in godwoken, will be fixed soon.

**Comment by RetricSu** [comment]
this should be fixed with this commit https://github.com/nervosnetwork/godwoken/commit/c1f4dff3dbf9e5cbb945e07d42b80fe65274617b in godwoken

**Comment by RetricSu** [comment]
so the error is changed. the data not found issue is gone, but instead we got a  `status_code 2`, this usually imply the op is denial by the EVM, need @TheWaWaR to take a look.

**Comment by TheWaWaR** [comment]
Will be fixed in follow PRs:
https://github.com/nervosnetwork/godwoken-polyjuice/pull/31
https://github.com/nervosnetwork/godwoken/pull/171

**Comment by TheWaWaR** [comment]
Please use follow dependencies:
* godwoken with [branch v0.2.x](https://github.com/nervosnetwork/godwoken/tree/v0.2.x)
* godwoken-polyjuice with [tag v0.6.0-rc3](https://github.com/nervosnetwork/godwoken-polyjuice/releases/tag/v0.6.0-rc3)

**Comment by Kuzirashi** [comment]
Still doesn't work. Same error.

I tried:
```
git clone
make gen-submodule-env
```

Now changed .manual.build.list.env ([mode] vars switched to true and changed godwoken+godwoken-polyjuice commits to what @TheWaWaR posted above) to:
```
####[mode]
MANUAL_BUILD_GODWOKEN=true
MANUAL_BUILD_WEB3=true

####[godwoken]
#info: tags/v0.2.1-0-gc18c768, c18c768 Fix clippy
GODWOKEN_URL=https://github.com/nervosnetwork/godwoken.git
GODWOKEN_BRANCH=v0.2.x
GODWOKEN_COMMIT=5c89aec

####[godwoken-web3]
#info: tags/v0.2.1-0-gf9665e1, f9665e1 Merge pull request #3 from nervosnetwork/return-eth-tx-hash
GODWOKEN_WEB3_URL=https://github.com/nervosnetwork/godwoken-web3.git
GODWOKEN_WEB3_BRANCH=main
GODWOKEN_WEB3_COMMIT=f9665e1

####[godwoken-polyjuice]
#info: tags/v0.6.0-rc1-0-g548d76e, 548d76e Merge pull request #29 from TheWaWaR/update-godwoken-scripts
GODWOKEN_POLYJUICE_URL=https://github.com/nervosnetwork/godwoken-polyjuice.git
GODWOKEN_POLYJUICE_BRANCH=v0.6.0
GODWOKEN_POLYJUICE_COMMIT=6eba914

####[godwoken-examples]
#info: heads/polyman-master-0-g200a17a, 200a17a Update server.json
GODWOKEN_EXAMPLES_URL=https://github.com/RetricSu/godwoken-examples.git
GODWOKEN_EXAMPLES_BRANCH=polyman-master
GODWOKEN_EXAMPLES_COMMIT=200a17a

####[godwoken-scripts]
#info: tags/v0.4.0-rc2-0-g83ae373, 83ae373 Merge pull request #22 from nervosnetwork/allow-user-unlock-withdrawal-phase2
GODWOKEN_SCRIPTS_URL=https://github.com/nervosnetwork/godwoken-scripts.git
GODWOKEN_SCRIPTS_BRANCH=master
GODWOKEN_SCRIPTS_COMMIT=83ae373
```

Then I ran:

```
make update-submodule
make rebuild-scripts
make init
make start
```

Then deployed contract, checked and same problem. Isn't custom polyjuice overriden by make init?

![image](https://user-images.githubusercontent.com/4950658/118997087-acc1b980-b988-11eb-9d1f-0c7952b21145.png)

**Comment by Kuzirashi** [comment]
I commented out lines with "git submodule update" in make install and prepare-build-scripts and ecrecover started working using versions provided by @TheWaWaR. 👏
